import React, { createContext, useContext, useState, useEffect } from 'react';

// DICTIONARY
// Ideally this grows into separate files, but for now we centralize it here.
const translations = {
    es: {
        // NAV
        nav_ecosystem: "ECOSISTEMA",
        nav_security: "SEGURIDAD",
        nav_mission: "NUESTRA MISIÓN",
        nav_manifesto: "MANIFIESTO",
        nav_download: "DESCARGAR APP",
        nav_terms: "TÉRMINOS",
        // HERO
        hero_title_prefix: "Red mundial de",
        hero_title_highlight: "emprendedores",
        hero_subtitle: "Ecosistema digital emprendedor, donde la tecnología y la innovación impulsan el crecimiento económico global.",
        hero_reveal_1: "Emprender ya no es imposible.",
        hero_reveal_2: "Solo faltaba la herramienta correcta.",
        // BIG BANG
        bigbang_title_1: "El universo emprendedor ha",
        bigbang_title_2: "dejado de ser un privilegio.",
        bigbang_desc_1: "Durante eones, el éxito estuvo reservado para unos pocos.",
        bigbang_desc_2: "Hoy, encendemos un nuevo cosmos digital donde las oportunidades son infinitas y accesibles para todos.",
        scroll: "SCROLL",
        // IGNITION
        ignition_title_1: "La secuencia de ignición",
        ignition_title_2: "ha comenzado.",
        ignition_desc: "La era de la exclusividad ha terminado. Una nueva galaxia de oportunidades te espera. ¿Vas a quedarte en tierra observando o vas a pilotar tu propio destino?",
        ignition_btn: "INICIAR DESPEGUE",
        // CLOSURE
        closure_line_1: "Hay un tipo de persona que nunca encaja del todo.",
        closure_line_2: "Mientras la mayoría se adapta, ellos se inquietan.",
        closure_tagline: "A los que no se conforman...",
        closure_btn: "OBTENER ACCESO ANTICIPADO",
        // ECOSYSTEM
        eco_title: "Nuestro Ecosistema",
        eco_subtitle: "Conoce la columna vertebral de la comunidad.",
        eco_drag: "Arrastra o mantén para pausar",
        eco_card_1_title: "Marketplace",
        eco_card_1_sub: "Venta de negocios y métricas verificadas",
        eco_card_1_desc: "Visibilidad basada en mérito financiero real. Un escaparate global donde la demanda encuentra a la oferta sin fricción.",
        eco_card_2_title: "Find Capital",
        eco_card_2_sub: "Encuentra inversores en todo el mundo",
        eco_card_2_desc: "Transformamos tu Pitch Deck en data estructurada. Conectamos tu visión con fondos que buscan exactamente tu perfil de riesgo.",
        eco_card_3_title: "Team Building",
        eco_card_3_sub: "No emprendas solo",
        eco_card_3_desc: "Encuentra co-fundadores técnicos. Firma acuerdos digitales instantáneos y distribuye equity de forma programática.",
        eco_card_4_title: "Smart Clips",
        eco_card_4_sub: "Inteligencia de mercado impulsada por IA",
        eco_card_4_desc: "Contenido generado por IA que impulsa la cultura emprendedora. Detecta tendencias y nichos de crecimiento antes que nadie.",
        eco_card_5_title: "Business Pricing",
        eco_card_5_sub: "Descubrimiento de beneficio justo",
        eco_card_5_desc: "Descubre el precio real de tu negocio con algoritmos predictivos. Obtén una ganancia justa basada en datos de mercado reales.",
        eco_card_6_title: "Community",
        eco_card_6_sub: "Gráfico de ecosistema descentralizado",
        eco_card_6_desc: "La red social del ecosistema emprendedor. Conecta con fundadores, valida ideas y escala tu red de contactos globalmente.",
        // INTELLIGENCE
        intel_title: "Copiloto Cognitivo",
        intel_subtitle: "Inteligencia Artificial tejida en el sistema nervioso.",
        intel_feat_1_title: "Redacción Legal",
        intel_feat_1_sub: "Contratos sin fricción",
        intel_feat_1_desc: "Cada operación está respaldada por smart contracts priorizando la seguridad y transparencia a los usuarios.",
        intel_feat_2_title: "Análisis Predictivo",
        intel_feat_2_sub: "Datos de mercado en tiempo real",
        intel_feat_2_desc: "Análisis en tiempo real de oportunidades para emprendedores e inversores, con el fin de democratizar su acceso.",
        intel_feat_3_title: "Algoritmos de Mercado",
        intel_feat_3_sub: "Reconocimiento de tendencias",
        intel_feat_3_desc: "Nuestro algoritmo aprende sobre tus preferencias para mostrarte oportunidades a tu medida.",
        intel_feat_4_title: "IA de Decisión",
        intel_feat_4_sub: "Modelado estratégico",
        intel_feat_4_desc: "Usamos inteligencia artificial para facilitar la toma de decisiones de los usuarios. Más tiempo y más beneficio...",
        // SECURITY
        sec_title: "Ecosistema Blindado",
        sec_subtitle: "Nos ocupamos de la seguridad de nuestros usuarios.",
        sec_feat_1_title: "KYC Biométrico",
        sec_feat_1_sub: "Eliminación de Perfiles Falsos",
        sec_feat_1_desc: "Sabemos quién es quién. Un entorno libre de fricción verificado biométricamente para garantizar interacciones humanas reales.",
        sec_feat_2_title: "Prueba de Fondos Real",
        sec_feat_2_sub: "Liquidez Verificada",
        sec_feat_2_desc: "El capital listado es real. Verificamos la solvencia de los inversores en tiempo real mediante APIs bancarias seguras.",
        sec_feat_3_title: "Mediación Integrada",
        sec_feat_3_sub: "Resolución de Disputas",
        sec_feat_3_desc: "Justicia digital codificada. Mediación integrada en cada contrato inteligente para resolver conflictos sin burocracia.",
        // FOOTER
        footer_rights: "Todos los derechos reservados.",
        footer_privacy: "Política de Privacidad",
        footer_terms: "Términos de Servicio",
        footer_contact: "Contacto",
        footer_brand_desc: "Ecosistema digital emprendedor, donde la tecnología y la innovación impulsan el crecimiento económico global.",
        footer_col_product: "Producto",
        footer_col_company: "Compañía",
        footer_col_legal: "Legal",
        footer_link_ecosystem: "Ecosistema",
        footer_link_manifesto: "Manifiesto",
        footer_link_about: "Sobre Nosotros",
        footer_link_careers: "Carreras",
        footer_link_cookies: "Cookies",
        footer_bottom_privacy: "Privacidad",
        footer_bottom_terms: "Términos",
        // MANIFESTO PAGE
        manifesto_p1: "Hay un tipo de persona que nunca encaja del todo. No porque sea un problema, sino porque el mundo que lo rodea siempre le queda chico.",
        manifesto_p2: "Son los que hacen preguntas incómodas, los que desarman las certezas ajenas, los que sienten que rendirse a lo establecido es una forma silenciosa de morir.",
        manifesto_p3_bold: "Ellos no buscan aprobación. Buscan propósito.",
        manifesto_p3_rest: " Mientras la mayoría se adapta, ellos se inquietan. Mientras otros aceptan reglas, ellos imaginan cómo reescribirlas.",
        manifesto_p4: "El futuro no se descubre… se construye.",
        manifesto_p5: "Son personas que fallan, sí. Pero cada caída se convierte en un mapa nuevo. Cada error, en una herramienta. Cada \"no se puede\", en una invitación a intentarlo de todas formas.",
        manifesto_p6: "Tienen una visión rara, incómoda, a veces perturbadora para quienes prefieren la comodidad al cambio. Pero esa visión es justamente lo que abre caminos donde antes no los había.",
        manifesto_p7: "Y el centro mundial de emprendedores es, en esencia, la obra de ese tipo de personas. Una constelación de mentes inquietas que eligieron no esperar, no pedir, no dudar. Eligieron hacer. Asi es como se concreto el final de una idea y comenzo un sueño.",
        manifesto_cta_text: "A los que no se conforman: este es su lugar.",
        manifesto_btn: "OBTENER ACCESO ANTICIPADO",
        // MISSION PAGE
        mission_label: "Nuestra Razón de Ser",
        mission_title: "Nacimos para desafiar la INERCIA.",
        mission_desc: "Esa fuerza invisible que mantiene al potencial humano atado al suelo. Existimos para eliminar la fricción entre una idea brillante y su ejecución.",
        mission_symbiosis: "Transformamos la soledad del emprendedor en una SIMBIOSIS GLOBAL.",
        mission_engine: "Un ecosistema vivo que actúa como el MOTOR CREATIVO de nuestra especie.",
        mission_convergence: "\"Un nexo donde la tecnología y la ambición convergen para acelerar la evolución misma de la humanidad.\"",
        mission_btn: "Obtener acceso anticipado",
        // SECURITY PAGE
        secpage_badge: "Infraestructura Blindada V4.0",
        secpage_hero_1: "Confianza",
        secpage_hero_2: "Matemática.",
        secpage_hero_desc: "Donde la seguridad no es una promesa, sino una prueba verificable. Protegemos tu identidad con los estándares más rigurosos de la industria.",
        secpage_label_tech: "Tecnología",
        secpage_label_trust: "Confianza",
        secpage_label_risk: "Riesgo Mitigado",
        secpage_cta_title_1: "Tu seguridad es nuestra ",
        secpage_cta_title_2: "prioridad absoluta",
        secpage_cta_desc: "Únete a la plataforma donde los emprendedores operan con total tranquilidad.",
        secpage_cta_btn: "Obtener Acceso Anticipado",
        secpage_p1_title: "Detección Anti-Scam",
        secpage_p1_sub: "Protocolo Centinela",
        secpage_p1_what: "Protección proactiva mediante análisis heurístico en tiempo real.",
        secpage_p1_structure: "Motor de IA que monitorea patrones de interacción anómalos y contratos maliciosos.",
        secpage_p1_benefit: "Bloqueo preventivo de intentos de phishing y rug-pulls antes de que ocurran.",
        secpage_p1_problem: "El fraude digital es la principal barrera de adopción en ecosistemas financieros descentralizados.",
        secpage_p2_title: "Identidad Soberana",
        secpage_p2_sub: "Estándar KYC/AML",
        secpage_p2_what: "Validación de identidad de grado bancario sin sacrificar privacidad.",
        secpage_p2_structure: "Integración con proveedores globales de biometría y verificación documental (GDPR Compliant).",
        secpage_p2_benefit: "Un entorno libre de bots y actores maliciosos, donde cada participante es real y verificable.",
        secpage_p2_problem: "El anonimato total facilita la impunidad y reduce la confianza institucional.",
        secpage_p3_title: "Auditoría Continua",
        secpage_p3_sub: "Seguridad On-Chain",
        secpage_p3_what: "Verificación matemática constante de la integridad de los contratos.",
        secpage_p3_structure: "Auditorías de terceros líderes (CertiK/OpenZeppelin) y programas Bug Bounty activos.",
        secpage_p3_benefit: "Garantía matemática de que los fondos solo se mueven según las reglas preestablecidas.",
        secpage_p3_problem: "Los errores en el código (bugs) pueden resultar en pérdidas irreversibles de capital.",
        secpage_p4_title: "Justicia Descentralizada",
        secpage_p4_sub: "Sistema de Mediación",
        secpage_p4_what: "Resolución de disputas imparcial basada en teoría de juegos.",
        secpage_p4_structure: "Tribunal digital donde jurados independientes analizan evidencias on-chain.",
        secpage_p4_benefit: "Resolución rápida y justa de conflictos comerciales sin depender de jurisdicciones lentas.",
        secpage_p4_problem: "Los sistemas legales tradicionales son costosos, lentos e ineficientes para la economía digital.",
        secpage_p5_title: "Penalizaciones",
        secpage_p5_sub: "Slashing Económico",
        secpage_p5_what: "Castigo automático e inmediato para el comportamiento malicioso.",
        secpage_p5_structure: "Mecanismo de 'Skin in the Game' donde los validadores pierden su stake si actúan deshonestamente.",
        secpage_p5_benefit: "Alineación total de incentivos: atacar la red es matemáticamente no rentable.",
        secpage_p5_problem: "Sin consecuencias económicas inmediatas, el comportamiento ético es opcional.",
        // DOWNLOAD PAGE
        dl_badge: "Disponible Globalmente",
        dl_title_1: "El ecosistema en",
        dl_title_2: "tu bolsillo.",
        dl_desc: "Accede a capital, gestiona inversiones y conéctate con emprendedores verificados desde cualquier lugar. La infraestructura WEC nativa en iOS y Android.",
        dl_appstore_sub: "Download on the",
        dl_playstore_sub: "Get it on",
        dl_also: "También disponible como",
        dl_webapp: "Web App",
        // ECOSYSTEM PAGE
        ecopage_hero_1: "Infraestructura del",
        ecopage_hero_2: "Nuevo Mundo",
        ecopage_hero_desc: "Cada componente del ecosistema ha sido diseñado para democratizar el acceso a oportunidades de negocio, talento y capital.",
        ecopage_label_structure: "Estructura",
        ecopage_label_benefit: "Beneficio",
        ecopage_label_problem: "Problema",
        ecopage_btn: "OBTENER ACCESO ANTICIPADO",
        ecopage_s1_title: "Marketplace", ecopage_s1_sub: "LIQUIDEZ SIN FRICCIÓN",
        ecopage_s1_what: "Un mercado secundario descentralizado donde startups y negocios tradicionales se compran y venden con la misma facilidad que una acción.",
        ecopage_s1_structure: "Utilizamos contratos inteligentes para el escrow de fondos y la transferencia de propiedad. La verificación de métricas se realiza on-chain para garantizar transparencia absoluta.",
        ecopage_s1_benefit: "Founders obtienen liquidez inmediata (Exit) sin esperar años a una IPO. Inversores acceden a flujo de caja verificado.",
        ecopage_s1_problem: "La venta de empresas privadas es un proceso lento (6-12 meses), costoso (brokers) y opaco.",
        ecopage_s2_title: "Find Capital", ecopage_s2_sub: "MATCHING ALGORÍTMICO",
        ecopage_s2_what: "Una plataforma de levantamiento de capital que conecta a fundadores con inversores basándose en tesis de inversión y datos, no en 'a quién conoces'.",
        ecopage_s2_structure: "Transformamos tu Pitch Deck en data estructurada. Nuestro motor de emparejamiento analiza miles de tesis de inversión para encontrar el fit perfecto.",
        ecopage_s2_benefit: "Acceso a capital global las 24/7. Cierra rondas en semanas, no meses.",
        ecopage_s2_problem: "El Fundraising tradicional es un juego de insiders, ineficiente y lleno de sesgos geográficos.",
        ecopage_s3_title: "Team Building", ecopage_s3_sub: "SOCIOS, NO EMPLEADOS",
        ecopage_s3_what: "El sistema definitivo para encontrar co-fundadores y talento clave dispuestos a trabajar por equity.",
        ecopage_s3_structure: "Perfiles verificados con historial de ejecución. Acuerdos de vesting generados y firmados digitalmente en la plataforma.",
        ecopage_s3_benefit: "Construye un equipo 'A-Player' sin quemar caja inicial. Alineación de incentivos total a largo plazo.",
        ecopage_s3_problem: "La soledad del fundador y la dificultad (y costo legal) de estructurar equipos co-fundadores sólidos.",
        ecopage_s4_title: "Smart Clips", ecopage_s4_sub: "INTELIGENCIA DE MERCADO",
        ecopage_s4_what: "Contenido de alto valor generado por IA que destila las tendencias más importantes del ecosistema emprendedor.",
        ecopage_s4_structure: "Agentes autónomos escanean miles de fuentes (news, papers, social) y generan resúmenes visuales de alto impacto.",
        ecopage_s4_benefit: "Mantente a la vanguardia sin ruido. Insights accionables para tu negocio en segundos.",
        ecopage_s4_problem: "La sobrecarga de información (infoxicación) hace imposible distinguir la señal del ruido.",
        ecopage_s5_title: "Business Pricing", ecopage_s5_sub: "VALUACIÓN OBJETIVA",
        ecopage_s5_what: "El estándar de oro para la valuación de negocios digitales y tradicionales.",
        ecopage_s5_structure: "Modelos de Machine Learning entrenados con datos de transacciones reales, ajustados por sector, crecimiento y riesgo.",
        ecopage_s5_benefit: "Elimina la especulación. Entra a una negociación con un precio defendible y justo.",
        ecopage_s5_problem: "La subjetividad extrema en las valuaciones mata acuerdos viables antes de empezar.",
        ecopage_s6_title: "Community", ecopage_s6_sub: "RED DE CONFIANZA",
        ecopage_s6_what: "Más que una red social, un grafo de reputación donde emprendedores e inversores validan su trayectoria.",
        ecopage_s6_structure: "Identidad soberana y sistema de reputación on-chain. Conexiones P2P directas.",
        ecopage_s6_benefit: "Validación social instantánea. Networking de calidad sin intermediarios ni gatekeepers.",
        ecopage_s6_problem: "La fragmentación del ecosistema hace que el valor de tu red esté limitado a tu ubicación física.",
        // GESTURE UI
        gesture_grabbing: "Arrastra fuera",
        gesture_ready: "Cierra el puño",
        gesture_looking: "Buscando manos...",
        // GENERIC
        loading: "Cargando..."
    },
    en: {
        // NAV
        nav_ecosystem: "ECOSYSTEM",
        nav_security: "SECURITY",
        nav_mission: "OUR MISSION",
        nav_manifesto: "MANIFESTO",
        nav_download: "DOWNLOAD APP",
        nav_terms: "TERMS",
        // HERO
        hero_title_prefix: "Global network of",
        hero_title_highlight: "entrepreneurs",
        hero_subtitle: "Digital entrepreneurial ecosystem, where technology and innovation drive global economic growth.",
        hero_reveal_1: "Entrepreneurship is no longer impossible.",
        hero_reveal_2: "The only missing piece was the right tool.",
        // BIG BANG
        bigbang_title_1: "The entrepreneurial universe has",
        bigbang_title_2: "ceased to be a privilege.",
        bigbang_desc_1: "For aeons, success was reserved for a few.",
        bigbang_desc_2: "Today, we ignite a new digital cosmos where opportunities are infinite and accessible to all.",
        scroll: "SCROLL",
        // IGNITION
        ignition_title_1: "The ignition sequence",
        ignition_title_2: "has begun.",
        ignition_desc: "The era of exclusivity is over. A new galaxy of opportunities awaits. Will you stay on the ground watching or will you pilot your own destiny?",
        ignition_btn: "INITIATE LAUNCH",
        // CLOSURE
        closure_line_1: "There is a type of person who never quite fits in.",
        closure_line_2: "While the majority adapts, they get restless.",
        closure_tagline: "To those who do not settle...",
        closure_btn: "GET EARLY ACCESS",
        // ECOSYSTEM
        eco_title: "Our Ecosystem",
        eco_subtitle: "Meet the backbone of the community.",
        eco_drag: "Drag or hover to pause",
        eco_card_1_title: "Marketplace",
        eco_card_1_sub: "Worldwide business selling & Verified Metrics",
        eco_card_1_desc: "Visibility based on real financial merit. A global showcase where demand meets supply without friction.",
        eco_card_2_title: "Find Capital",
        eco_card_2_sub: "Find investors around the world",
        eco_card_2_desc: "We transform your Pitch Deck into structured data. We connect your vision with funds looking for exactly your risk profile.",
        eco_card_3_title: "Team Building",
        eco_card_3_sub: "Don't start a startup alone",
        eco_card_3_desc: "Find technical co-founders. Sign instant digital agreements and distribute equity programmatically.",
        eco_card_4_title: "Smart Clips",
        eco_card_4_sub: "AI-Driven Market Intelligence",
        eco_card_4_desc: "AI-generated content driving entrepreneurial culture. Detect trends and growth niches before anyone else.",
        eco_card_5_title: "Business Pricing",
        eco_card_5_sub: "Fair Profit Discovery",
        eco_card_5_desc: "Discover the real price of your business with predictive algorithms. Get a fair profit based on real market data.",
        eco_card_6_title: "Community",
        eco_card_6_sub: "Decentralized Ecosystem Graph",
        eco_card_6_desc: "The social network of the entrepreneurial ecosystem. Connect with founders, validate ideas and scale your network globally.",
        // INTELLIGENCE
        intel_title: "Cognitive Copilot",
        intel_subtitle: "Artificial Intelligence woven into the nervous system.",
        intel_feat_1_title: "Legal Drafting",
        intel_feat_1_sub: "Zero-Friction Contracts",
        intel_feat_1_desc: "Every operation is backed by smart contracts prioritizing user security and transparency.",
        intel_feat_2_title: "Predictive Analysis",
        intel_feat_2_sub: "Real-Time Market Data",
        intel_feat_2_desc: "Real-time analysis of opportunities for entrepreneurs and investors, aimed at democratizing access.",
        intel_feat_3_title: "Market Algorithms",
        intel_feat_3_sub: "Trend Recognition",
        intel_feat_3_desc: "Our algorithm learns about your preferences to show you opportunities tailored to you.",
        intel_feat_4_title: "Decision AI",
        intel_feat_4_sub: "Strategic Modeling",
        intel_feat_4_desc: "We use artificial intelligence to facilitate user decision-making processes. More time and more profit...",
        // SECURITY
        sec_title: "Shielded Ecosystem",
        sec_subtitle: "We take care of our users' security.",
        sec_feat_1_title: "Biometric KYC",
        sec_feat_1_sub: "Fake Profile Elimination",
        sec_feat_1_desc: "We know who is who. A friction-free environment biometrically verified to ensure real human interactions.",
        sec_feat_2_title: "Real-time Proof of Funds",
        sec_feat_2_sub: "Verified Liquidity",
        sec_feat_2_desc: "Listed capital is real. We verify investor solvency in real-time through secure banking APIs.",
        sec_feat_3_title: "Integrated Mediation",
        sec_feat_3_sub: "Dispute Resolution",
        sec_feat_3_desc: "Encoded digital justice. Mediation integrated into every smart contract to resolve conflicts without bureaucracy.",
        // FOOTER
        footer_rights: "All rights reserved.",
        footer_privacy: "Privacy Policy",
        footer_terms: "Terms of Service",
        footer_contact: "Contact",
        footer_brand_desc: "Digital entrepreneurial ecosystem, where technology and innovation drive global economic growth.",
        footer_col_product: "Product",
        footer_col_company: "Company",
        footer_col_legal: "Legal",
        footer_link_ecosystem: "Ecosystem",
        footer_link_manifesto: "Manifesto",
        footer_link_about: "About Us",
        footer_link_careers: "Careers",
        footer_link_cookies: "Cookies",
        footer_bottom_privacy: "Privacy",
        footer_bottom_terms: "Terms",
        // MANIFESTO PAGE
        manifesto_p1: "There is a type of person who never quite fits in. Not because they are a problem, but because the world around them always feels too small.",
        manifesto_p2: "They are the ones who ask uncomfortable questions, who dismantle others' certainties, who feel that surrendering to the status quo is a quiet form of dying.",
        manifesto_p3_bold: "They don't seek approval. They seek purpose.",
        manifesto_p3_rest: " While the majority adapts, they get restless. While others accept rules, they imagine how to rewrite them.",
        manifesto_p4: "The future is not discovered… it is built.",
        manifesto_p5: "They are people who fail, yes. But every fall becomes a new map. Every mistake, a tool. Every \"it can't be done,\" an invitation to try anyway.",
        manifesto_p6: "They have a rare vision, uncomfortable, sometimes unsettling for those who prefer comfort over change. But that vision is precisely what opens paths where none existed before.",
        manifesto_p7: "And the World Entrepreneurs Centre is, in essence, the work of those kinds of people. A constellation of restless minds who chose not to wait, not to ask, not to hesitate. They chose to act. That is how the end of an idea became the beginning of a dream.",
        manifesto_cta_text: "To those who do not settle: this is your place.",
        manifesto_btn: "GET EARLY ACCESS",
        // MISSION PAGE
        mission_label: "Our Reason for Being",
        mission_title: "We were born to challenge INERTIA.",
        mission_desc: "That invisible force that keeps human potential grounded. We exist to eliminate the friction between a brilliant idea and its execution.",
        mission_symbiosis: "We transform entrepreneur loneliness into a GLOBAL SYMBIOSIS.",
        mission_engine: "A living ecosystem that acts as the CREATIVE ENGINE of our species.",
        mission_convergence: "\"A nexus where technology and ambition converge to accelerate humanity's own evolution.\"",
        mission_btn: "Get early access",
        // SECURITY PAGE
        secpage_badge: "Shielded Infrastructure V4.0",
        secpage_hero_1: "Mathematical",
        secpage_hero_2: "Trust.",
        secpage_hero_desc: "Where security is not a promise, but verifiable proof. We protect your identity with the most rigorous industry standards.",
        secpage_label_tech: "Technology",
        secpage_label_trust: "Trust",
        secpage_label_risk: "Mitigated Risk",
        secpage_cta_title_1: "Your security is our ",
        secpage_cta_title_2: "absolute priority",
        secpage_cta_desc: "Join the platform where entrepreneurs operate with total peace of mind.",
        secpage_cta_btn: "Get Early Access",
        secpage_p1_title: "Anti-Scam Detection",
        secpage_p1_sub: "Sentinel Protocol",
        secpage_p1_what: "Proactive protection through real-time heuristic analysis.",
        secpage_p1_structure: "AI engine that monitors anomalous interaction patterns and malicious contracts.",
        secpage_p1_benefit: "Preventive blocking of phishing attempts and rug-pulls before they occur.",
        secpage_p1_problem: "Digital fraud is the main adoption barrier in decentralized financial ecosystems.",
        secpage_p2_title: "Sovereign Identity",
        secpage_p2_sub: "KYC/AML Standard",
        secpage_p2_what: "Banking-grade identity validation without sacrificing privacy.",
        secpage_p2_structure: "Integration with global biometric and document verification providers (GDPR Compliant).",
        secpage_p2_benefit: "A bot-free environment free of malicious actors, where every participant is real and verifiable.",
        secpage_p2_problem: "Total anonymity facilitates impunity and reduces institutional trust.",
        secpage_p3_title: "Continuous Auditing",
        secpage_p3_sub: "On-Chain Security",
        secpage_p3_what: "Constant mathematical verification of contract integrity.",
        secpage_p3_structure: "Leading third-party audits (CertiK/OpenZeppelin) and active Bug Bounty programs.",
        secpage_p3_benefit: "Mathematical guarantee that funds only move according to pre-established rules.",
        secpage_p3_problem: "Code errors (bugs) can result in irreversible capital losses.",
        secpage_p4_title: "Decentralized Justice",
        secpage_p4_sub: "Mediation System",
        secpage_p4_what: "Impartial dispute resolution based on game theory.",
        secpage_p4_structure: "Digital court where independent jurors analyze on-chain evidence.",
        secpage_p4_benefit: "Fast and fair resolution of commercial conflicts without relying on slow jurisdictions.",
        secpage_p4_problem: "Traditional legal systems are expensive, slow, and inefficient for the digital economy.",
        secpage_p5_title: "Penalties",
        secpage_p5_sub: "Economic Slashing",
        secpage_p5_what: "Automatic and immediate punishment for malicious behavior.",
        secpage_p5_structure: "'Skin in the Game' mechanism where validators lose their stake if they act dishonestly.",
        secpage_p5_benefit: "Total alignment of incentives: attacking the network is mathematically unprofitable.",
        secpage_p5_problem: "Without immediate economic consequences, ethical behavior is optional.",
        // DOWNLOAD PAGE
        dl_badge: "Available Globally",
        dl_title_1: "The ecosystem in",
        dl_title_2: "your pocket.",
        dl_desc: "Access capital, manage investments, and connect with verified entrepreneurs from anywhere. WEC infrastructure native on iOS and Android.",
        dl_appstore_sub: "Download on the",
        dl_playstore_sub: "Get it on",
        dl_also: "Also available as",
        dl_webapp: "Web App",
        // ECOSYSTEM PAGE
        ecopage_hero_1: "Infrastructure of the",
        ecopage_hero_2: "New World",
        ecopage_hero_desc: "Every component of the ecosystem has been designed to democratize access to business opportunities, talent, and capital.",
        ecopage_label_structure: "Structure",
        ecopage_label_benefit: "Benefit",
        ecopage_label_problem: "Problem",
        ecopage_btn: "GET EARLY ACCESS",
        ecopage_s1_title: "Marketplace", ecopage_s1_sub: "FRICTIONLESS LIQUIDITY",
        ecopage_s1_what: "A decentralized secondary market where startups and traditional businesses are bought and sold as easily as a stock.",
        ecopage_s1_structure: "We use smart contracts for fund escrow and ownership transfer. Metric verification is done on-chain to ensure absolute transparency.",
        ecopage_s1_benefit: "Founders get immediate liquidity (Exit) without waiting years for an IPO. Investors access verified cash flow.",
        ecopage_s1_problem: "Selling private companies is a slow (6-12 months), expensive (brokers), and opaque process.",
        ecopage_s2_title: "Find Capital", ecopage_s2_sub: "ALGORITHMIC MATCHING",
        ecopage_s2_what: "A capital-raising platform connecting founders with investors based on investment theses and data, not 'who you know'.",
        ecopage_s2_structure: "We transform your Pitch Deck into structured data. Our matching engine analyzes thousands of investment theses to find the perfect fit.",
        ecopage_s2_benefit: "Access to global capital 24/7. Close rounds in weeks, not months.",
        ecopage_s2_problem: "Traditional Fundraising is an insider's game, inefficient and full of geographic biases.",
        ecopage_s3_title: "Team Building", ecopage_s3_sub: "PARTNERS, NOT EMPLOYEES",
        ecopage_s3_what: "The definitive system for finding co-founders and key talent willing to work for equity.",
        ecopage_s3_structure: "Verified profiles with execution track record. Vesting agreements generated and digitally signed on the platform.",
        ecopage_s3_benefit: "Build an 'A-Player' team without burning initial cash. Total long-term incentive alignment.",
        ecopage_s3_problem: "Founder loneliness and the difficulty (and legal cost) of structuring solid co-founder teams.",
        ecopage_s4_title: "Smart Clips", ecopage_s4_sub: "MARKET INTELLIGENCE",
        ecopage_s4_what: "High-value AI-generated content distilling the most important trends in the entrepreneurial ecosystem.",
        ecopage_s4_structure: "Autonomous agents scan thousands of sources (news, papers, social) and generate high-impact visual summaries.",
        ecopage_s4_benefit: "Stay ahead without noise. Actionable insights for your business in seconds.",
        ecopage_s4_problem: "Information overload (infoxication) makes it impossible to distinguish signal from noise.",
        ecopage_s5_title: "Business Pricing", ecopage_s5_sub: "OBJECTIVE VALUATION",
        ecopage_s5_what: "The gold standard for digital and traditional business valuation.",
        ecopage_s5_structure: "Machine Learning models trained on real transaction data, adjusted by sector, growth, and risk.",
        ecopage_s5_benefit: "Eliminate speculation. Enter a negotiation with a defensible and fair price.",
        ecopage_s5_problem: "Extreme subjectivity in valuations kills viable deals before they even start.",
        ecopage_s6_title: "Community", ecopage_s6_sub: "TRUST NETWORK",
        ecopage_s6_what: "More than a social network, a reputation graph where entrepreneurs and investors validate their track record.",
        ecopage_s6_structure: "Sovereign identity and on-chain reputation system. Direct P2P connections.",
        ecopage_s6_benefit: "Instant social validation. Quality networking without intermediaries or gatekeepers.",
        ecopage_s6_problem: "Ecosystem fragmentation limits the value of your network to your physical location.",
        // GESTURE UI
        gesture_grabbing: "Drag outside",
        gesture_ready: "Close your fist",
        gesture_looking: "Looking for hands...",
        // GENERIC
        loading: "Loading..."
    }
};

const LanguageContext = createContext(null);

export const LanguageProvider = ({ children }) => {
    // Default to ES, or detect browser? User said currently hardcoded ES.
    // We start with ES.
    const [language, setLanguage] = useState('es');

    const toggleLanguage = () => {
        setLanguage(prev => prev === 'es' ? 'en' : 'es');
    };

    const t = (key) => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) throw new Error("useLanguage must be used within a LanguageProvider");
    return context;
};
